//------------------------------------------------------------------------
// Copyright(c) 2023 Test Company.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"testpluginbundle.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"testpluginbundle VST3 (64Bit)"
#else
#define stringFileDescription	"testpluginbundle VST3"
#endif
#define stringCompanyName		"Test Company\0"
#define stringLegalCopyright	"Copyright(c) 2023 Test Company."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
